pipeline {
	
	agent any

	tools{
		maven 'Maven 3.6.3'
	}

	stages{
		
		stage(build){
			when{
				changeset "**/result/**"
			}
			steps{
				echo "Compiling worker"

				dir('worker'){
					sh 'mvn compile'
				}
			}
		}
		stage(test){
			when{
				changeset "**/result/**"
			}
			steps{
				echo "Testing worker"

				dir('worker'){
					sh 'mvn clean test'
				}
			}
		}
		stage(package){
			when{
				changeset "**/result/**"
			}
			steps{
				echo "Packaging worker"

				dir('worker'){
					sh 'mvn package -DskipTests'
				}
			}
		}
	}
}
